language: cpp
compiler: gcc

branches:
    only:
        - master

script:
    - make test

notifications:
    email: false

#after_script:
#        - if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then cat /home/travis/build/yasukei/libstrut/cov-int/build-log.txt; fi
